### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by mpkuchera** [ATTPC/deep-learning-event-classification#2]
Readme lacks package versions and an example for running the training script, making the code difficult to install and run.

**Comment by rystrauss** [comment]
@mpkuchera I think the only package version of any importance is `tensorflow<2.0`, which I can add to the README. Which training script(s) are you having issues with? Do you want something more than the `--help` message provided by the Click CLI?

**Comment by mpkuchera** [comment]
Yeah I think the tensor flow version caused someone an issue recently... and maybe an example of running with the defaults? I think you need CLIs minimum?

**Comment by rystrauss** [comment]
@mpkuchera Ok I will update the README with the TensorFlow version and an example of running with defaults. The scripts all already have CLIs.
